theme: minima
title: Learning is a fun
author: Pawan
email: pawanpb100@gmail.com
description: > Welcome to my first commit site. It just for learning purpose.

# social links
twitter_username: Pawan_Bhatt2409 # DO NOT include the @ character, or else the build will fail!
github_username:  Pawan152431 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
